Repository openshift/ibm-roks-toolkit, pull requests merged in 2021-03, with the labels that each got.

#154 Portieris 4.5 backport
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm

#144 Add support for OpenShift 4.7
  assets/kube-apiserver/config.yaml
  assets/kube-apiserver/default-audit-policy.yaml
  assets/kube-apiserver/kube-apiserver-default-audit-policy.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/oauth-apiserver/audit-policy.yaml
  assets/oauth-apiserver/oauth-apiserver-auditpolicy.yaml
  assets/oauth-apiserver/oauth-apiserver-configmap.yaml
  assets/oauth-apiserver/oauth-apiserver-deployment.yaml
  assets/oauth-apiserver/oauth-apiserver-secret.yaml
  assets/oauth-apiserver/oauth-apiserver-service.yaml
  assets/oauth-apiserver/oauth-apiserver-user-endpoint.yaml
  assets/oauth-apiserver/oauth-apiserver-user-service.yaml
  assets/oauth-apiserver/service-template.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  pkg/render/manifests.go
Labels: approved, lgtm

#155 Update registry references
  .secrets.baseline
  DockerCITest
  cluster.yaml.example
Labels: approved, lgtm

#158 Set/Update tls-cipher-suites (1.2) for components
  .gitignore
  .secrets.baseline
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#159 Support setting kube-apiserver log verbosity
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm

#165 [release-4.6] Support setting kube-apiserver log verbosity
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm

#167 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#166 [release-4.5] Support setting kube-apiserver log verbosity
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm

#162 Add/Remove tls-cipher-suites (1.2) for components
  .gitignore
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  assets/openshift-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, needs-ok-to-test

#161 Add/Update tls-cipher-suites (1.3) for components
  .gitignore
  .secrets.baseline
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  assets/openshift-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#163 Add tls-cipher-suites to openshift-apiserver and openshift-controller…
  assets/openshift-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#170 Add/Update tls-cipher-suites (1.3) values for release-4.6
  .gitignore
  .secrets.baseline
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  assets/openshift-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#169 Update defaultMode 0640 for all secret volume definitions
  .secrets.baseline
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/control-plane-operator/cp-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-apiserver/oauth-apiserver-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#177 Update defaultMode 0640 for all secret volume definitions: release-4.6
  .secrets.baseline
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/control-plane-operator/cp-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#180 Add --profiling=false to kube-controller-manager - release-4.6
  .secrets.baseline
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#179 Add --profiling=false to kube-controller-manager
  .secrets.baseline
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#178 Update defaultMode 0640 for all secret volume definitions: release-4.5
  .secrets.baseline
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/control-plane-operator/cp-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#181 Add --profiling=false to kube-controller-manager - release-4.5
  .secrets.baseline
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test

#185 Add ingress-to-route controller role/rolebinding to bootstrap manifests
  assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml
  assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm

#184 [release 4.6] Add openshift-oauth-apiserver namespace to bootstrap namespaces
  assets/cluster-bootstrap/00000_namespaces-needed-for-monitoring.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm

#187 Revert back to 1.2 tls-cipher-suites for 4.6
  .secrets.baseline
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  assets/openshift-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm
