Repository openshift/ibm-roks-toolkit, pull requests merged in 2022-06, with the labels that each got.

#521 Update OpenShift assets for 4.11
  assets/cluster-bootstrap/api-usage.yaml
  assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
  assets/cluster-bootstrap/cluster-network-01-crd.yaml
  assets/cluster-bootstrap/csr_approver_clusterrole.yaml
  assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
  assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
  assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
  assets/cluster-bootstrap/trust_distribution_role.yaml
  assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#527 Update Dockerfile to point to correct 1.18 image
  Dockerfile
  Dockerfile.cpoperator
  Dockerfile.metrics
Labels: lgtm, approved

#529 Bump kube dependencies to v1.24.1
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/group/authenticated_group_adder.go
  vendor/k8s.io/apiserver/pkg/authentication/group/group_adder.go
  vendor/k8s.io/apiserver/pkg/authentication/group/token_group_adder.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/kubectl/pkg/util/templates/templater.go
  vendor/modules.txt
Labels: lgtm, approved

#531 [release-4.10] Update OpenShift assets
  Dockerfile.metrics
  assets/cluster-bootstrap/api-usage.yaml
  assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
  assets/cluster-bootstrap/cluster-network-01-crd.yaml
  assets/cluster-bootstrap/csr_approver_clusterrole.yaml
  assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
  assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
  assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
  assets/cluster-bootstrap/trust_distribution_role.yaml
  assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#532 Publish release 20220602
  release-date
Labels: lgtm, approved

#541 Trivial Change
  README.md
Labels: lgtm, approved

#545 Publish release 20220606
  release-date
Labels: lgtm, approved

#555 bump v4.11 release
  release-date
Labels: lgtm, ok-to-test, approved

#564 ROKS 4.11: Update roks toolkit image policies
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/roks-metrics/roks-metrics-deployment.yaml
  assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#565 Remove/Update enable-default-cluster-version and leader-elect-resource-lock flags
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: needs-ok-to-test, lgtm, approved

#575 Create new roks-toolkit release based on new image policies
  release-date
Labels: lgtm, ok-to-test, approved

#576 ROKS 4.10 toolkit release with updated image policies
  release-date
Labels: lgtm, ok-to-test, approved

#582 Reduce gosec concurrency to minimize CI resource utilization
  Makefile
Labels: lgtm, approved

#583 Add exemption to PodSecurity config, remove from enable-admission-plugins
  assets/kube-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#589 Enable most gosec checks
  Makefile
  pkg/controllers/cmca/configmap_observer.go
  pkg/controllers/openshiftapiserver/controller.go
  pkg/controllers/openshiftcontrollermanager/operator_client.go
  pkg/metrics/server.go
  pkg/metricspusher/pusher.go
Labels: lgtm, approved

#593 ROKS 4.11 Toolkit release with new ClusterVersion resource
  release-date
Labels: lgtm, ok-to-test, approved

#595 Render random cluster UUID by default
  assets/cluster-bootstrap/cluster-version.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  pkg/render/funcs.go
  pkg/render/manifests.go
Labels: lgtm, approved

#596 Cleanup code owners
  OWNERS
Labels: lgtm, approved

#598 Publish release 20220623
  release-date
Labels: lgtm, approved

#606 Add comment to cluster version bootstrap resource
  assets/cluster-bootstrap/cluster-version.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved
