Repository openshift/ibm-roks-toolkit, pull requests merged in 2022-01, with the labels that each got.

#322 Fix the template of the default IngressController
  assets/cluster-bootstrap/cluster-ingresscontrollers-02-config.yaml
  pkg/assets/bindata.go
Labels: needs-ok-to-test, lgtm, approved

#304 reduce worker cert duration to 2 years per fscloud requirements
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#327 PR Test: Build binaries and test rendering manifests
  Makefile
  empty-pull-secret.txt
  hack/test.sh
Labels: lgtm, approved

#332 Update cluster example manifest to align with current usage
  cluster.yaml.example
Labels: lgtm, approved

#335 Update cluster example manifest to align with current usage
  cluster.yaml.example
Labels: lgtm, approved

#336 Update cluster example manifest to align with current usage
  cluster.yaml.example
Labels: lgtm, approved

#337 Update cluster example manifest to align with current usage
  cluster.yaml.example
Labels: lgtm, approved

#338 Removed unused PKI manifests
  assets/cluster-version-operator/cluster-version-operator-configmap.yaml
  assets/cluster-version-operator/cluster-version-operator-secret.yaml
  assets/common/service-network-admin-kubeconfig-secret.yaml
  assets/control-plane-operator/cp-operator-configmap.yaml
  assets/kube-apiserver/kube-apiserver-configmap.yaml
  assets/kube-apiserver/kube-apiserver-secret.yaml
  assets/kube-controller-manager/kube-controller-manager-configmap.yaml
  assets/kube-controller-manager/kube-controller-manager-secret.yaml
  assets/kube-scheduler/kube-scheduler-secret.yaml
  assets/oauth-apiserver/oauth-apiserver-configmap.yaml
  assets/oauth-apiserver/oauth-apiserver-secret.yaml
  assets/oauth-openshift/oauth-server-configmap.yaml
  assets/oauth-openshift/oauth-server-secret.yaml
  assets/openshift-apiserver/openshift-apiserver-configmap.yaml
  assets/openshift-apiserver/openshift-apiserver-secret.yaml
  assets/openshift-controller-manager/openshift-controller-manager-configmap.yaml
  assets/openshift-controller-manager/openshift-controller-manager-secret.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#340 Changed controlPlaneTopology to External
  .secrets.baseline
  assets/cluster-bootstrap/cluster-infrastructure-02-config.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#342 update minReadySeconds and terminationGracePeriod for ROKS master com…
  .secrets.baseline
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-apiserver/oauth-apiserver-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#344 Update minReadySeconds and terminationGracePeriod for ROKS 4.8
  .secrets.baseline
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-apiserver/oauth-apiserver-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#345 Update minReadySeconds and terminationGracePeriod for ROKS 4.7
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-apiserver/oauth-apiserver-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#346 Update minReadySeconds and terminationGracePeriod for ROKS 4.6
  .secrets.baseline
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#347 Add liveness/readiness probes to components
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#349 ROKS v4.9: Disable Kubernetes API server profiling
  .secrets.baseline
  assets/kube-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#351 Support new oauth setup for OpenShift version 4.9
  assets/kube-apiserver/config.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/oauth-apiserver/oauth-apiserver-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved
