Repository openshift/ibm-roks-toolkit, pull requests merged in 2023-10, with the labels that each got.

#822 Add openshift-network-operator namespace and network-node-identity co…
  assets/cluster-bootstrap/00000_openshift-network-operator-ns.yaml
  assets/cluster-bootstrap/network-node-identity-configmap.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#824 bump release
  release-date
Labels: lgtm, ok-to-test, approved

#829 Update wait-for-images.sh to support manifest list images
  hack/wait-for-images.sh
Labels: lgtm, approved

#831 Update wait-for-images.sh to support manifest list images
  hack/wait-for-images.sh
Labels: lgtm, approved

#833 Testing fix for wait-for-images
  hack/wait-for-images.sh
Labels: lgtm, approved

#846 Use latest wait-for-image.sh for 4.13 and earlier
  hack/wait-for-images.sh
Labels: lgtm, ok-to-test, approved

#851 [release-4.13] Publish release 20231010
  release-date
Labels: lgtm, approved

#855 Revert network-node-identity configmap fix
  assets/cluster-bootstrap/00000_openshift-network-operator-ns.yaml
  assets/cluster-bootstrap/network-node-identity-configmap.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#857 bump release
  release-date
Labels: needs-ok-to-test, lgtm, approved

#859 add liveness probes and leader election
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/route-controller-manager/config.yaml
  assets/route-controller-manager/route-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#861 bump release
  release-date
Labels: needs-ok-to-test, lgtm, approved

#813 Add minimum TLS version to components in ROKS v4.14+
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/openshift-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  assets/route-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved
