Repository openshift/ibm-roks-toolkit, pull requests merged in 2023-11, with the labels that each got.

#864 Currency updates for 4.14
  assets/cluster-bootstrap/api-usage.yaml
  assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
  assets/cluster-bootstrap/cluster-network-01-crd.yaml
  assets/cluster-bootstrap/csr_approver_clusterrole.yaml
  assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
  assets/cluster-bootstrap/deployer-clusterrole.yaml
  assets/cluster-bootstrap/deployer-clusterrolebinding.yaml
  assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
  assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
  assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml
  assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
  assets/cluster-bootstrap/podsecurity-alert.yaml
  assets/cluster-bootstrap/trust_distribution_role.yaml
  assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
  cmd/control-plane-operator/main.go
  pkg/assets/bindata.go
  pkg/config/file.go
  pkg/metricspusher/pusher.go
  pkg/render/rendercontext.go
Labels: lgtm, approved

#868 Additional currency updates for 4.14
  assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml
  assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml
  assets/cluster-bootstrap/leader-ingress-to-route-controller-role.yaml
  assets/cluster-bootstrap/leader-ingress-to-route-controller-rolebinding.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#872 [release-4.13] Publish release 20231102
  release-date
Labels: lgtm, approved

#876 Set default pod security enforcement to privileged
  assets/kube-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#880 Set goaway-chance on kube-apiserver to 0.001
  assets/kube-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#882 Publish release 20231108
  release-date
Labels: lgtm, approved

#887 Publish release
  release-date
Labels: lgtm, approved

#884 Add ROKS v4.14 etcd operator config
  assets/cluster-bootstrap/etcd-operator-config.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#894 Konnectivity integration - followup changes based on review commpents
  assets/konnectivity/konnectivity-server-services.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  cluster.using.konnectivity.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#893 Build release with Konnectivity support
  release-date
Labels: lgtm, approved

#897 Add shutdown-duration-delay to openshift-apiserver
  assets/openshift-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#898 Add roles for the new privileged namespaces PSA syncer controller in …
  assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrole.yaml
  assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrolebinding.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#900 Add roles for the new privileged namespaces PSA syncer controller in …
  assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrole.yaml
  assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrolebinding.yaml
  pkg/assets/bindata.go
Labels: needs-ok-to-test, lgtm, approved

#901 bump release
  release-date
Labels: lgtm, ok-to-test, approved

#903 Add oauth CLI client for web based login
  .secrets.baseline
  assets/oauth-openshift/oauth-cli-client.yaml
  pkg/assets/bindata.go
  pkg/render/manifests.go
Labels: lgtm, approved

#904 Update Konnectivity to honor config replicas
  assets/konnectivity/konnectivity-agent-control-plane-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#906 Publish release
  release-date
Labels: lgtm, approved

#909 fix quotation mark for ClusterID
  assets/konnectivity/konnectivity-agent-control-plane-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#911 Publish release
  release-date
Labels: lgtm, approved
