Repository openshift/ibm-roks-toolkit, pull requests merged in 2024-05, with the labels that each got.

#990 Publish release 20240501
  release-date
Labels: lgtm, ok-to-test, approved

#992 [release-4.16] Publish release 20240501
  release-date
Labels: lgtm, ok-to-test, approved

#993 Publish release 20240503
  release-date
Labels: lgtm, approved

#996 Add oc whoami to release scripts
  hack/tag-release-images.sh
  hack/wait-for-images.sh
Labels: lgtm, approved

#1001 Publish release 20240507
  release-date
Labels: lgtm, approved

#1003 Remove flowcontrol.apiserver.k8s.io/v1alpha1 from runtime config
  .secrets.baseline
  assets/kube-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#1004 Render IBM Cloud managed cluster profile for KAS bootstrap
  .secrets.baseline
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#1005 Publish release 20240513 for 4.16
  release-date
Labels: lgtm, approved

#1009 Publish release 20240514
  release-date
Labels: lgtm, approved

#1011 [release-4.15] Publish release 20240514
  release-date
Labels: lgtm, approved

#1012 [release-4.14] Publish release 20240514
  release-date
Labels: lgtm, approved

#1015 Remove '-operator' from machine config crd copy command
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#1017 bump release
  release-date
Labels: needs-ok-to-test, lgtm, approved

#1019 Exclude NoUpgrade CRDs
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#1021 Increase KCM node-monitor-grace-period
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: lgtm, approved

#1023 [release-4.15] Increase KCM node-monitor-grace-period
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: lgtm, approved

#1024 [release-4.14] Increase KCM node-monitor-grace-period
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: lgtm, approved

#1026 [release-4.13] Increase KCM node-monitor-grace-period
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: lgtm, approved

#1027 [release-4.12] Increase KCM node-monitor-grace-period
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: lgtm, approved

#1028 Bump toolkit release
  release-date
Labels: lgtm, approved

#1030 [release-4.15] Bump toolkit release
  release-date
Labels: lgtm, approved

#1034 ROKS v4.16: Set default pod security enforcement to restricted to align with open…
  assets/kube-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#1037 ROKS v4.16: Set default pod security enforcement to restricted to align with openshift defaults.
  assets/kube-apiserver/config.yaml
  assets/openshift-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: lgtm, ok-to-test, approved

#1038 bump release
  release-date
Labels: lgtm, ok-to-test, approved
